version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password  # Replace with your password
      POSTGRES_DB: wannago
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com  # pgAdmin login email
      PGADMIN_DEFAULT_PASSWORD: admin_password  # pgAdmin login password
    ports:
      - "8080:80"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data:
